### ISSUE TITLE
how can i change the size for clock

### ISSUE THREAD

**Issue by qiuxiaolian** [zippyui/react-date-picker#100] opened 2016-06-24 04:09 UTC
i want to change the size for clock, is there anybody know?

**Comment by qiuxiaolian** [comment] 2016-06-24 06:11
I set DateField  locale="zh-cn", it looks fine，like this 
![2016-06-24 2 04 31](https://cloud.githubusercontent.com/assets/15975145/16329459/4497d6b6-3a15-11e6-8c31-a0a90c0444c5.png)
but when i click the month it change to en,like this 
![2016-06-24 2 10 09](https://cloud.githubusercontent.com/assets/15975145/16329469/6667e06a-3a15-11e6-83f9-44bbb52c2bb4.png)
i want a date-picker with chinese!

**Comment by radubrehar** [comment] 2016-06-24 08:35
Can you share a snippet of code? I cannot seem to reproduce the bug. Thanks

**Comment by dev-zippyui** [comment] 2016-07-19 11:55
Since we cannot reproduce this, we're closing the issue.
Feel free to reopen if you encounter this, and make sure to provide more details.

**Closed by dev-zippyui** 2016-07-19 11:55 UTC
