### ISSUE TITLE
Error message in console

### ISSUE THREAD

**Issue by tomhah** [zippyui/react-date-picker#88] opened 2016-06-15 10:30 UTC
When using the MonthView component, I get an error in the console:
Each child in an array or iterator should have a unique "key" prop. Check the render method of `BasicMonthView`. See https://fb.me/react-warning-keys for more information.

**Comment by radubrehar** [comment] 2016-06-15 12:34
I'm trying to reproduce that but with no success. Can you please share your context/code snippet. What version `react` & `react-date-picker` are you using? Try updating the datepicker to the latest version on npm, `5.3.8`

**Comment by tomhah** [comment] 2016-06-15 13:04
I am using 5.3.8 of the react-date-picker and 0.14.0 of react.

```javascript
import {MonthView, TransitionView} from 'react-date-picker';
```
```html
<TransitionView>
    <MonthView
              renderDay={(date) => {
                const formattedDate = date.dateMoment.format('YYYY-MM-DD');

                if (this.props.customer.data.feeds[formattedDate]) {
                  return (
                      <div
                        key={date.text}
                        className={classNames(date.className, styles.hasData)}
                        onClick={date.onClick}
                        onKeyUp={date.onKeyUp}>
                        {date.children}
                      </div>
                  );
                }

                return (
                    <div key={date.text} className={date.className} onClick={date.onClick} onKeyUp={date.onKeyUp}>
                      {date.children}
                    </div>
                );
              }}
                weekDayNames={() => {return ['Søn', 'Man', 'Tir', 'Ons', 'Tor', 'Fre', 'Lør'];}}
                todayText="I dag"
                gotoSelectedText="Gå til valgt dato"
                weekStartDay={1}
                minDate="2015-04-04"
                maxDate="2016-10-10"
                date={selectedDate}
                onChange={(date) => this.props.signals.home.selectedDateChanged({date})}
                />
</TransitionView>
```

**Comment by radubrehar** [comment] 2016-06-15 13:13
Thanks, got it! It was because of the `renderDay` prop you specified. Please update to `5.3.9` just released on npm with the fix for this.

**Comment by tomhah** [comment] 2016-06-15 13:17
Works like a charm, awesome! :) This is the best date-picker for React in my opinion! Works brilliantly for my use case. Thanks!

**Closed** 2016-06-15 13:18 UTC

**Comment by radubrehar** [comment] 2016-06-15 13:20
Thanks for sharing the love!
