### ISSUE TITLE
Does not work with IE11

### ISSUE THREAD

**Issue by rodryquintero** [zippyui/react-date-picker#47] opened 2015-09-17 19:51 UTC
When using IE 11, the contents of the date picker (day cells) are blank. Here is an image of what I mean.

![react date picker ie 11](https://cloud.githubusercontent.com/assets/1271370/9944220/86fcb50a-5d4b-11e5-89e1-e63fa8b80ead.png)

**Comment by radubrehar** [comment] 2015-09-17 20:00
Hm... thanks for reporting! Thanks because of some css prefixes not being applied correctly. I'll update date picker to  use `autoprefixer` an this will fix the issue.

**Comment by rodryquintero** [comment] 2015-09-17 20:01
Wow, thanks for the quick reply. Looking forward to see this updated.

**Comment by ichbinedgar** [comment] 2015-10-13 15:12
Hi, it does not work on IE9 too. Maybe you should add a disclaimer explaining which browsers are supported.

**Comment by rodryquintero** [comment] 2015-10-13 17:09
@radubrehar if there is anything I can do to help let me know. I don't know much about css vendor prefixes but I can research about them.

**Comment by fterlid** [comment] 2015-11-03 11:43
Is there a workaround for this issue? Or will it be fixed in the near future?

**Comment by radubrehar** [comment] 2015-11-06 21:44
Can you have a look into this now? We've just released  `3.1.8` on npm. Also thanks @koddsson for #53 fixing the example page.

We've also integrated autoprefixer, so you should be fine now.

**Comment by koddsson** [comment] 2015-11-09 10:03
I just spun up a windows 10 machine running IE11 on @saucelabs and can confirm that it's running correctly on the demo page after #53 got merged :smile:

![0003screenshot](https://cloud.githubusercontent.com/assets/318208/11030888/cdbec0fe-86c8-11e5-9803-5f26732e867c.png)

**Comment by radubrehar** [comment] 2015-11-09 10:05
Great news!

**Comment by fterlid** [comment] 2015-11-09 14:54
Strange, it doesn't work for me. I have to override some css to make it work (scss below):

`.date-picker {`
`    flex: 1 0 auto !important;` 
`    .dp-body, .dp-table, .dp-row, .dp-cell, .dp-nav-table, .dp-nav-table .dp-nav-cell {`
`        flex: 1 0 auto !important;`
`    }`
`}`

I'm using the hackerone theme.

It could be that my use case is a weird one, given that @koddsson has verified it to work.

**Comment by radubrehar** [comment] 2015-11-09 15:09
Does the default theme work for you?

**Comment by fterlid** [comment] 2015-11-09 15:22
No, just tested with the default theme. I've cleared the npm cache and set the dependency to `"react-date-picker": "^3.1.8",` in package.json, so it should have the correct version.

**Comment by radubrehar** [comment] 2015-11-09 15:27
Have you given a height to the picker? Does your example work correctly in other browsers?

**Comment by fterlid** [comment] 2015-11-09 15:32
It works as expected in other browsers. Haven't set an explicit height. Is there a style prop i've missed perhaps?

**Comment by radubrehar** [comment] 2015-11-09 15:55
You have to either give it an explicit height, or make it fill its container, or flex it somehow.

```style={{height: 400}}``

**Comment by fterlid** [comment] 2015-11-09 16:14
Ok, thanks! I'll give it a go. Perhaps this should be noted in the readme?

**Comment by koddsson** [comment] 2015-11-09 16:19
The blog post in #53 has some nice points and tips for the height bug in IE11 @fterlid. It could be added to the README for future reference.

**Comment by radubrehar** [comment] 2015-11-09 17:06
A PR is welcomed on that, as this week we are busy with launching  https://www.npmjs.com/package/react-date-field, integrating the datepicker with input field

**Comment by radubrehar** [comment] 2015-12-01 15:10
Closing this as there's no new updates and problems reported in IE

**Closed by radubrehar** 2015-12-01 15:10 UTC

**Comment by climboid** [comment] 2017-01-17 15:53
Still seeing issues with IE11
![ie11-bug](https://cloud.githubusercontent.com/assets/672364/22027833/523dbffe-dc92-11e6-94cf-c98413c8f9ca.png)

Seems like the months are collapsing on each other as well as the years.
Using ^5.3.28

**Comment by bwobst** [comment] 2017-03-22 12:21
@climboid did you ever find a solution? I'm having the same issue.

**Comment by climboid** [comment] 2017-03-22 18:43
@bwobst It ended up being a fix in flexbox styles. I'm reaching out to the dev who fixed it see if he can post his solution here

**Comment by rgabs** [comment] 2017-03-23 00:13
@bwobst This issue is addressed in the below PR.

The issue is with the default flex properties on IE.

https://github.com/zippytech/react-date-picker/pull/240

**Comment by bwobst** [comment] 2017-03-23 01:41
@rgabs Thanks.  Apparently it wasn't included in master (or whichever branch was installed by default) so I added those styles manually and or worked like a charm.

**Comment by rgabs** [comment] 2017-03-23 01:44
Yes that's because the PR is not merged yet.
